participants_matrix:
  el:
    - el_type: geth
      el_image: ethpandaops/geth:prague-devnet-6
    # - el_type: reth
    #   el_image: ethpandaops/reth:main
    - el_type: nethermind
      el_image: ethpandaops/nethermind:master
    - el_type: erigon
      el_image: ethpandaops/erigon:pectra6
    # - el_type: besu
    #   el_image: ethpandaops/besu:main
  cl:
    - cl_type: lighthouse
      cl_image: ethpandaops/lighthouse:unstable
    # - cl_type: teku
    #   cl_image: consensys/teku:develop
    # - cl_type: nimbus
    #   cl_image: ethpandaops/nimbus-eth2:unstable
    - cl_type: lodestar
      cl_image: ethpandaops/lodestar:unstable
    # - cl_type: grandine
    #   cl_image: ethpandaops/grandine:devnet5
    - cl_type: prysm
      cl_image: ethpandaops/prysm-beacon-chain:develop
      vc_image: ethpandaops/prysm-validator:develop

network_params:
  preset: minimal
  electra_fork_epoch: 1
  min_validator_withdrawability_delay: 1
  shard_committee_period: 1
  churn_limit_quotient: 16
  genesis_delay: 240
additional_services:
  - dora
  - spamoor_blob
  - tx_spammer
  - assertoor
dora_params:
  image: "ethpandaops/dora:master-latest"
spamoor_blob_params:
  throughput: 10 
  max_blobs: 2  
  max_pending: 40 

assertoor_params:
  image: "ethpandaops/assertoor:master"
  tests:
    - file: antithesis/tests/pectra-devnet-6/execution-spec-tests.yaml
    - file: antithesis/tests/pectra-devnet-6/kurtosis/all.yaml
    - file: antithesis/tests/pectra-devnet-6/blockhash-test-with-rpc-call.yaml
    - file: antithesis/tests/pectra-devnet-6/eip7002-all.yaml
    - file: antithesis/tests/pectra-devnet-6/eip7251-all.yaml