name: Build and Push Config + Assertoor Image to Antithesis Registry

on:
  push:
    branches:
      - main  # Trigger this action on push to the main branch
  workflow_dispatch:  # Allows manual trigger
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Login to Antithesis Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}
        username: _json_key
        password: ${{ secrets.JSON_LOGIN_KEY }}

    - name: Build and push config image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile.config
        push: true
        tags: |
          us-central1-docker.pkg.dev/molten-verve-216720/ethereum-repository/config:antithesis-latest,
          ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.REPOSITORY }}/config:${{ github.sha }}

    - name: Build and push assertoor image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile.assertoor
        push: true
        tags: |
          us-central1-docker.pkg.dev/molten-verve-216720/ethereum-repository/assertoor:antithesis-latest,
          us-central1-docker.pkg.dev/molten-verve-216720/ethereum-repository/assertoor:${{ github.sha }}