name: Trigger Antithesis exploration

env:
  REGISTRY: us-central1-docker.pkg.dev
  REPOSITORY: molten-verve-216720/ethereum-repository

on: 
  workflow_dispatch:
    inputs:
      test:
        description: 'Test name'
        required: false
        default: ''
        type: string
      config_image:
        description: 'Config image'
        required: true
        default: us-central1-docker.pkg.dev/molten-verve-216720/ethereum-repository/config:antithesis-latest
        type: string
      images:
        description: 'System images (separate with ;)'
        required: true
        default: us-central1-docker.pkg.dev/molten-verve-216720/ethereum-repository/assertoor:antithesis-lates;us-central1-docker.pkg.dev/molten-verve-216720/ethereum-repository/geth:antithesis-assertions;docker.io/chainsafe/lodestar:v1.22.0
        type: string
      duration:
        description: 'Duration (exploration hours)'
        required: true
        type: int
        default: 1.0
      configuration:
        description: 'Configuration file'
        required: true
        type: string
        default: ".github/tests/minimal.yaml"
      description:
        description: 'Test run description (avoid quotes, please!)'
        required: true
        type: string
        default: "No description provided"
      email:
        description: 'Additional email notification recipient (separate with ;)'
        required: true
        type: string
        default: ""
      
  # push:
  #   branches:
  #     - main  # Trigger this action on push to the main branch

jobs:
  antithesis:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    # Run Antithesis Tests
    - name: Run Antithesis Tests
      uses: antithesishq/antithesis-trigger-action@main
      with:
        notebook_name: ethereum
        tenant: ethereum
        username: ${{ secrets.ANTITHESIS_USERNAME }}
        password: ${{ secrets.ANTITHESIS_PASSWORD }}
        github_token: ${{ secrets.GH_PAT }}
        config_image: ${{ inputs.config_image }}
        images: ${{ inputs.images }}
        description: ${{ inputs.description }}
        email_recipients: ${{ inputs.email }}
        test_name: ${{ inputs.test}}
        additional_parameters: |-
          custom.configuration=${{ inputs.configuration }}
          custom.duration = ${{ inputs.duration }}
